/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// DlocalBalance
    /// </summary>
    [DataContract]
    public partial class DlocalBalance :  IEquatable<DlocalBalance>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlocalBalance" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public DlocalBalance()
        {
        }
        
        /// <summary>
        /// The currency of this balance
        /// </summary>
        /// <value>The currency of this balance</value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public string Currency { get; private set; }

        /// <summary>
        /// The available balance for the given currency
        /// </summary>
        /// <value>The available balance for the given currency</value>
        [DataMember(Name="available_balance", EmitDefaultValue=false)]
        public decimal? AvailableBalance { get; private set; }

        /// <summary>
        /// The balance at end of previous day
        /// </summary>
        /// <value>The balance at end of previous day</value>
        [DataMember(Name="previous_day_closing_balance", EmitDefaultValue=false)]
        public decimal? PreviousDayClosingBalance { get; private set; }

        /// <summary>
        /// Current date
        /// </summary>
        /// <value>Current date</value>
        [DataMember(Name="current_balance_date", EmitDefaultValue=false)]
        public string CurrentBalanceDate { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DlocalBalance {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  AvailableBalance: ").Append(AvailableBalance).Append("\n");
            sb.Append("  PreviousDayClosingBalance: ").Append(PreviousDayClosingBalance).Append("\n");
            sb.Append("  CurrentBalanceDate: ").Append(CurrentBalanceDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DlocalBalance);
        }

        /// <summary>
        /// Returns true if DlocalBalance instances are equal
        /// </summary>
        /// <param name="input">Instance of DlocalBalance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DlocalBalance input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.AvailableBalance == input.AvailableBalance ||
                    (this.AvailableBalance != null &&
                    this.AvailableBalance.Equals(input.AvailableBalance))
                ) && 
                (
                    this.PreviousDayClosingBalance == input.PreviousDayClosingBalance ||
                    (this.PreviousDayClosingBalance != null &&
                    this.PreviousDayClosingBalance.Equals(input.PreviousDayClosingBalance))
                ) && 
                (
                    this.CurrentBalanceDate == input.CurrentBalanceDate ||
                    (this.CurrentBalanceDate != null &&
                    this.CurrentBalanceDate.Equals(input.CurrentBalanceDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.AvailableBalance != null)
                    hashCode = hashCode * 59 + this.AvailableBalance.GetHashCode();
                if (this.PreviousDayClosingBalance != null)
                    hashCode = hashCode * 59 + this.PreviousDayClosingBalance.GetHashCode();
                if (this.CurrentBalanceDate != null)
                    hashCode = hashCode * 59 + this.CurrentBalanceDate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
