/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// OpenCorporatesSenderUpdate
    /// </summary>
    [DataContract]
    public partial class OpenCorporatesSenderUpdate :  IEquatable<OpenCorporatesSenderUpdate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenCorporatesSenderUpdate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OpenCorporatesSenderUpdate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenCorporatesSenderUpdate" /> class.
        /// </summary>
        /// <param name="id">Id of the sender to be updated with Open Corporates search results (required).</param>
        /// <param name="country">Alpha2 code of the country that the company to be searched is registered in (required).</param>
        /// <param name="registrationNumber">Registration number of the company to be searched (required).</param>
        /// <param name="state">State/Province for countries that require it..</param>
        public OpenCorporatesSenderUpdate(Guid? id = default(Guid?), string country = default(string), string registrationNumber = default(string), string state = default(string))
        {
            this.Id = id;
            this.Country = country;
            this.RegistrationNumber = registrationNumber;
            this.State = state;
        }
        
        /// <summary>
        /// Id of the sender to be updated with Open Corporates search results
        /// </summary>
        /// <value>Id of the sender to be updated with Open Corporates search results</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Alpha2 code of the country that the company to be searched is registered in
        /// </summary>
        /// <value>Alpha2 code of the country that the company to be searched is registered in</value>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// Registration number of the company to be searched
        /// </summary>
        /// <value>Registration number of the company to be searched</value>
        [DataMember(Name="registration_number", EmitDefaultValue=false)]
        public string RegistrationNumber { get; set; }

        /// <summary>
        /// State/Province for countries that require it.
        /// </summary>
        /// <value>State/Province for countries that require it.</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OpenCorporatesSenderUpdate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  RegistrationNumber: ").Append(RegistrationNumber).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OpenCorporatesSenderUpdate);
        }

        /// <summary>
        /// Returns true if OpenCorporatesSenderUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of OpenCorporatesSenderUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OpenCorporatesSenderUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.RegistrationNumber == input.RegistrationNumber ||
                    (this.RegistrationNumber != null &&
                    this.RegistrationNumber.Equals(input.RegistrationNumber))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.RegistrationNumber != null)
                    hashCode = hashCode * 59 + this.RegistrationNumber.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
