/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The entity type of the recipient.  For ZAR personal payouts valid options are: - &#x60;person&#x60;: Person  For ZAR business payouts valid options are: - &#x60;sole_proprietorship&#x60;: Sole Proprietorship - &#x60;privately_owned_company&#x60;: Privately Owned Company (Limited Company) - &#x60;publicly_owned_company&#x60;: Publicly Owned Company (PLC) - &#x60;government_owned_entity&#x60;: Government Owned Entity Trusts - &#x60;partnership&#x60;: Partnership - &#x60;go&#x60;: GO (Majority Owned Subsidiary of State-Owned Company) - &#x60;financial_institution&#x60;: Financial Institution
    /// </summary>
    /// <value>The entity type of the recipient.  For ZAR personal payouts valid options are: - &#x60;person&#x60;: Person  For ZAR business payouts valid options are: - &#x60;sole_proprietorship&#x60;: Sole Proprietorship - &#x60;privately_owned_company&#x60;: Privately Owned Company (Limited Company) - &#x60;publicly_owned_company&#x60;: Publicly Owned Company (PLC) - &#x60;government_owned_entity&#x60;: Government Owned Entity Trusts - &#x60;partnership&#x60;: Partnership - &#x60;go&#x60;: GO (Majority Owned Subsidiary of State-Owned Company) - &#x60;financial_institution&#x60;: Financial Institution</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodLegalEntityTypeEnum
    {
        /// <summary>
        /// Enum Person for value: person
        /// </summary>
        [EnumMember(Value = "person")]
        Person = 1,

        /// <summary>
        /// Enum Soleproprietorship for value: sole_proprietorship
        /// </summary>
        [EnumMember(Value = "sole_proprietorship")]
        Soleproprietorship = 2,

        /// <summary>
        /// Enum Privatelyownedcompany for value: privately_owned_company
        /// </summary>
        [EnumMember(Value = "privately_owned_company")]
        Privatelyownedcompany = 3,

        /// <summary>
        /// Enum Publiclyownedcompany for value: publicly_owned_company
        /// </summary>
        [EnumMember(Value = "publicly_owned_company")]
        Publiclyownedcompany = 4,

        /// <summary>
        /// Enum Governmentownedentity for value: government_owned_entity
        /// </summary>
        [EnumMember(Value = "government_owned_entity")]
        Governmentownedentity = 5,

        /// <summary>
        /// Enum Partnership for value: partnership
        /// </summary>
        [EnumMember(Value = "partnership")]
        Partnership = 6,

        /// <summary>
        /// Enum Go for value: go
        /// </summary>
        [EnumMember(Value = "go")]
        Go = 7,

        /// <summary>
        /// Enum Financialinstitution for value: financial_institution
        /// </summary>
        [EnumMember(Value = "financial_institution")]
        Financialinstitution = 8

    }

}
