/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The country for the pickup or mobile payout.  For XOF cash pickup, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;ML&#x60;: Mali - &#x60;SN&#x60;: Senegal  For XOF mobile payout, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;SN&#x60;: Senegal
    /// </summary>
    /// <value>The country for the pickup or mobile payout.  For XOF cash pickup, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;ML&#x60;: Mali - &#x60;SN&#x60;: Senegal  For XOF mobile payout, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;SN&#x60;: Senegal</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodCountryEnum
    {
        /// <summary>
        /// Enum CI for value: CI
        /// </summary>
        [EnumMember(Value = "CI")]
        CI = 1,

        /// <summary>
        /// Enum ML for value: ML
        /// </summary>
        [EnumMember(Value = "ML")]
        ML = 2,

        /// <summary>
        /// Enum SN for value: SN
        /// </summary>
        [EnumMember(Value = "SN")]
        SN = 3,

        /// <summary>
        /// Enum NG for value: NG
        /// </summary>
        [EnumMember(Value = "NG")]
        NG = 4,

        /// <summary>
        /// Enum MA for value: MA
        /// </summary>
        [EnumMember(Value = "MA")]
        MA = 5,

        /// <summary>
        /// Enum TZ for value: TZ
        /// </summary>
        [EnumMember(Value = "TZ")]
        TZ = 6,

        /// <summary>
        /// Enum GH for value: GH
        /// </summary>
        [EnumMember(Value = "GH")]
        GH = 7,

        /// <summary>
        /// Enum UG for value: UG
        /// </summary>
        [EnumMember(Value = "UG")]
        UG = 8,

        /// <summary>
        /// Enum KE for value: KE
        /// </summary>
        [EnumMember(Value = "KE")]
        KE = 9,

        /// <summary>
        /// Enum NJ for value: NJ
        /// </summary>
        [EnumMember(Value = "NJ")]
        NJ = 10,

        /// <summary>
        /// Enum EU for value: EU
        /// </summary>
        [EnumMember(Value = "EU")]
        EU = 11,

        /// <summary>
        /// Enum GB for value: GB
        /// </summary>
        [EnumMember(Value = "GB")]
        GB = 12,

        /// <summary>
        /// Enum ZA for value: ZA
        /// </summary>
        [EnumMember(Value = "ZA")]
        ZA = 13,

        /// <summary>
        /// Enum EG for value: EG
        /// </summary>
        [EnumMember(Value = "EG")]
        EG = 14

    }

}
