/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The movile provider of the recipient:  For XOF valid options are: - &#x60;orange&#x60;: Orange - &#x60;tigo&#x60;: Tigo  For GHS valid options are: - &#x60;mtn&#x60;: MTN - &#x60;airtel&#x60;: Airtel - &#x60;tigo&#x60;: Tigo - &#x60;vodafone&#x60;: Vodafone
    /// </summary>
    /// <value>The movile provider of the recipient:  For XOF valid options are: - &#x60;orange&#x60;: Orange - &#x60;tigo&#x60;: Tigo  For GHS valid options are: - &#x60;mtn&#x60;: MTN - &#x60;airtel&#x60;: Airtel - &#x60;tigo&#x60;: Tigo - &#x60;vodafone&#x60;: Vodafone</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodMobileProviderEnum
    {
        /// <summary>
        /// Enum Orange for value: orange
        /// </summary>
        [EnumMember(Value = "orange")]
        Orange = 1,

        /// <summary>
        /// Enum Tigo for value: tigo
        /// </summary>
        [EnumMember(Value = "tigo")]
        Tigo = 2,

        /// <summary>
        /// Enum Mtn for value: mtn
        /// </summary>
        [EnumMember(Value = "mtn")]
        Mtn = 3,

        /// <summary>
        /// Enum Airtel for value: airtel
        /// </summary>
        [EnumMember(Value = "airtel")]
        Airtel = 4,

        /// <summary>
        /// Enum Vodafone for value: vodafone
        /// </summary>
        [EnumMember(Value = "vodafone")]
        Vodafone = 5

    }

}
