/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The cash provider for the pickup: For XOF valid options are: - &#x60;wizall&#x60;: Wizall
    /// </summary>
    /// <value>The cash provider for the pickup: For XOF valid options are: - &#x60;wizall&#x60;: Wizall</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodCashProviderEnum
    {
        /// <summary>
        /// Enum Wari for value: wari
        /// </summary>
        [EnumMember(Value = "wari")]
        Wari = 1,

        /// <summary>
        /// Enum Wizall for value: wizall
        /// </summary>
        [EnumMember(Value = "wizall")]
        Wizall = 2

    }

}
