/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TransferZero.Sdk.Client.OpenAPIDateConverter;

namespace TransferZero.Sdk.Model
{
    /// <summary>
    /// The country for USD::Bank payouts.  Valid options are: - NG
    /// </summary>
    /// <value>The country for USD::Bank payouts.  Valid options are: - NG</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PayoutMethodCountryEnumUSDBank
    {
        /// <summary>
        /// Enum NG for value: NG
        /// </summary>
        [EnumMember(Value = "NG")]
        NG = 1

    }

}
