/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing BankAccountDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BankAccountDetailsTests
    {
        // TODO uncomment below to declare an instance variable for BankAccountDetails
        //private BankAccountDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BankAccountDetails
            //instance = new BankAccountDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BankAccountDetails
        /// </summary>
        [Test]
        public void BankAccountDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BankAccountDetails
            //Assert.IsInstanceOfType<BankAccountDetails> (instance, "variable 'instance' is a BankAccountDetails");
        }


        /// <summary>
        /// Test the property 'PayinCcy'
        /// </summary>
        [Test]
        public void PayinCcyTest()
        {
            // TODO unit test for the property 'PayinCcy'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Test]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'BankAddress'
        /// </summary>
        [Test]
        public void BankAddressTest()
        {
            // TODO unit test for the property 'BankAddress'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Test]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'BicOrSwift'
        /// </summary>
        [Test]
        public void BicOrSwiftTest()
        {
            // TODO unit test for the property 'BicOrSwift'
        }
        /// <summary>
        /// Test the property 'SortCode'
        /// </summary>
        [Test]
        public void SortCodeTest()
        {
            // TODO unit test for the property 'SortCode'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'BranchName'
        /// </summary>
        [Test]
        public void BranchNameTest()
        {
            // TODO unit test for the property 'BranchName'
        }
        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Test]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'UnavailableMessage'
        /// </summary>
        [Test]
        public void UnavailableMessageTest()
        {
            // TODO unit test for the property 'UnavailableMessage'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
