/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing DlocalBalance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DlocalBalanceTests
    {
        // TODO uncomment below to declare an instance variable for DlocalBalance
        //private DlocalBalance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DlocalBalance
            //instance = new DlocalBalance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DlocalBalance
        /// </summary>
        [Test]
        public void DlocalBalanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DlocalBalance
            //Assert.IsInstanceOfType<DlocalBalance> (instance, "variable 'instance' is a DlocalBalance");
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Test]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'PreviousDayClosingBalance'
        /// </summary>
        [Test]
        public void PreviousDayClosingBalanceTest()
        {
            // TODO unit test for the property 'PreviousDayClosingBalance'
        }
        /// <summary>
        /// Test the property 'CurrentBalanceDate'
        /// </summary>
        [Test]
        public void CurrentBalanceDateTest()
        {
            // TODO unit test for the property 'CurrentBalanceDate'
        }

    }

}
