/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing OpenCorporatesSenderUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OpenCorporatesSenderUpdateRequestTests
    {
        // TODO uncomment below to declare an instance variable for OpenCorporatesSenderUpdateRequest
        //private OpenCorporatesSenderUpdateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OpenCorporatesSenderUpdateRequest
            //instance = new OpenCorporatesSenderUpdateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OpenCorporatesSenderUpdateRequest
        /// </summary>
        [Test]
        public void OpenCorporatesSenderUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenCorporatesSenderUpdateRequest
            //Assert.IsInstanceOfType<OpenCorporatesSenderUpdateRequest> (instance, "variable 'instance' is a OpenCorporatesSenderUpdateRequest");
        }


        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

    }

}
