/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodDetailsEGPBank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodDetailsEGPBankTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodDetailsEGPBank
        //private PayoutMethodDetailsEGPBank instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodDetailsEGPBank
            //instance = new PayoutMethodDetailsEGPBank();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodDetailsEGPBank
        /// </summary>
        [Test]
        public void PayoutMethodDetailsEGPBankInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodDetailsEGPBank
            //Assert.IsInstanceOfType<PayoutMethodDetailsEGPBank> (instance, "variable 'instance' is a PayoutMethodDetailsEGPBank");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Test]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }
        /// <summary>
        /// Test the property 'TransferReason'
        /// </summary>
        [Test]
        public void TransferReasonTest()
        {
            // TODO unit test for the property 'TransferReason'
        }

    }

}
