/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodDetailsXAFBank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodDetailsXAFBankTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodDetailsXAFBank
        //private PayoutMethodDetailsXAFBank instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodDetailsXAFBank
            //instance = new PayoutMethodDetailsXAFBank();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodDetailsXAFBank
        /// </summary>
        [Test]
        public void PayoutMethodDetailsXAFBankInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodDetailsXAFBank
            //Assert.IsInstanceOfType<PayoutMethodDetailsXAFBank> (instance, "variable 'instance' is a PayoutMethodDetailsXAFBank");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Test]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Test]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'BankCountry'
        /// </summary>
        [Test]
        public void BankCountryTest()
        {
            // TODO unit test for the property 'BankCountry'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Test]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }
        /// <summary>
        /// Test the property 'SortCode'
        /// </summary>
        [Test]
        public void SortCodeTest()
        {
            // TODO unit test for the property 'SortCode'
        }
        /// <summary>
        /// Test the property 'TransferReason'
        /// </summary>
        [Test]
        public void TransferReasonTest()
        {
            // TODO unit test for the property 'TransferReason'
        }

    }

}
