/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodDetailsBRLBank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodDetailsBRLBankTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodDetailsBRLBank
        //private PayoutMethodDetailsBRLBank instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodDetailsBRLBank
            //instance = new PayoutMethodDetailsBRLBank();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodDetailsBRLBank
        /// </summary>
        [Test]
        public void PayoutMethodDetailsBRLBankInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodDetailsBRLBank
            //Assert.IsInstanceOfType<PayoutMethodDetailsBRLBank> (instance, "variable 'instance' is a PayoutMethodDetailsBRLBank");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Test]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }
        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Test]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'BankAccountType'
        /// </summary>
        [Test]
        public void BankAccountTypeTest()
        {
            // TODO unit test for the property 'BankAccountType'
        }
        /// <summary>
        /// Test the property 'IdentityCardType'
        /// </summary>
        [Test]
        public void IdentityCardTypeTest()
        {
            // TODO unit test for the property 'IdentityCardType'
        }
        /// <summary>
        /// Test the property 'IdentityCardId'
        /// </summary>
        [Test]
        public void IdentityCardIdTest()
        {
            // TODO unit test for the property 'IdentityCardId'
        }
        /// <summary>
        /// Test the property 'TransferReason'
        /// </summary>
        [Test]
        public void TransferReasonTest()
        {
            // TODO unit test for the property 'TransferReason'
        }

    }

}
