/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PayoutMethodDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PayoutMethodDetailsTests
    {
        // TODO uncomment below to declare an instance variable for PayoutMethodDetails
        //private PayoutMethodDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayoutMethodDetails
            //instance = new PayoutMethodDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayoutMethodDetails
        /// </summary>
        [Test]
        public void PayoutMethodDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PayoutMethodDetails
            //Assert.IsInstanceOfType<PayoutMethodDetails> (instance, "variable 'instance' is a PayoutMethodDetails");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Test]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'BankAccountType'
        /// </summary>
        [Test]
        public void BankAccountTypeTest()
        {
            // TODO unit test for the property 'BankAccountType'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'MobileProvider'
        /// </summary>
        [Test]
        public void MobileProviderTest()
        {
            // TODO unit test for the property 'MobileProvider'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'TransferReason'
        /// </summary>
        [Test]
        public void TransferReasonTest()
        {
            // TODO unit test for the property 'TransferReason'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Test]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Test]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'BankCountry'
        /// </summary>
        [Test]
        public void BankCountryTest()
        {
            // TODO unit test for the property 'BankCountry'
        }
        /// <summary>
        /// Test the property 'CashProvider'
        /// </summary>
        [Test]
        public void CashProviderTest()
        {
            // TODO unit test for the property 'CashProvider'
        }
        /// <summary>
        /// Test the property 'SortCode'
        /// </summary>
        [Test]
        public void SortCodeTest()
        {
            // TODO unit test for the property 'SortCode'
        }
        /// <summary>
        /// Test the property 'Bic'
        /// </summary>
        [Test]
        public void BicTest()
        {
            // TODO unit test for the property 'Bic'
        }
        /// <summary>
        /// Test the property 'SenderIdentityCardType'
        /// </summary>
        [Test]
        public void SenderIdentityCardTypeTest()
        {
            // TODO unit test for the property 'SenderIdentityCardType'
        }
        /// <summary>
        /// Test the property 'SenderIdentityCardId'
        /// </summary>
        [Test]
        public void SenderIdentityCardIdTest()
        {
            // TODO unit test for the property 'SenderIdentityCardId'
        }
        /// <summary>
        /// Test the property 'SenderCityOfBirth'
        /// </summary>
        [Test]
        public void SenderCityOfBirthTest()
        {
            // TODO unit test for the property 'SenderCityOfBirth'
        }
        /// <summary>
        /// Test the property 'SenderCountryOfBirth'
        /// </summary>
        [Test]
        public void SenderCountryOfBirthTest()
        {
            // TODO unit test for the property 'SenderCountryOfBirth'
        }
        /// <summary>
        /// Test the property 'SenderGender'
        /// </summary>
        [Test]
        public void SenderGenderTest()
        {
            // TODO unit test for the property 'SenderGender'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'IdentityCardType'
        /// </summary>
        [Test]
        public void IdentityCardTypeTest()
        {
            // TODO unit test for the property 'IdentityCardType'
        }
        /// <summary>
        /// Test the property 'IdentityCardId'
        /// </summary>
        [Test]
        public void IdentityCardIdTest()
        {
            // TODO unit test for the property 'IdentityCardId'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'TransferReasonCode'
        /// </summary>
        [Test]
        public void TransferReasonCodeTest()
        {
            // TODO unit test for the property 'TransferReasonCode'
        }
        /// <summary>
        /// Test the property 'ContactFirstName'
        /// </summary>
        [Test]
        public void ContactFirstNameTest()
        {
            // TODO unit test for the property 'ContactFirstName'
        }
        /// <summary>
        /// Test the property 'ContactLastName'
        /// </summary>
        [Test]
        public void ContactLastNameTest()
        {
            // TODO unit test for the property 'ContactLastName'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'NatureOfBusiness'
        /// </summary>
        [Test]
        public void NatureOfBusinessTest()
        {
            // TODO unit test for the property 'NatureOfBusiness'
        }
        /// <summary>
        /// Test the property 'LegalEntityType'
        /// </summary>
        [Test]
        public void LegalEntityTypeTest()
        {
            // TODO unit test for the property 'LegalEntityType'
        }
        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Test]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }
        /// <summary>
        /// Test the property 'SwiftCode'
        /// </summary>
        [Test]
        public void SwiftCodeTest()
        {
            // TODO unit test for the property 'SwiftCode'
        }

    }

}
