/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing PoliticallyExposedPerson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PoliticallyExposedPersonTests
    {
        // TODO uncomment below to declare an instance variable for PoliticallyExposedPerson
        //private PoliticallyExposedPerson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PoliticallyExposedPerson
            //instance = new PoliticallyExposedPerson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PoliticallyExposedPerson
        /// </summary>
        [Test]
        public void PoliticallyExposedPersonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PoliticallyExposedPerson
            //Assert.IsInstanceOfType<PoliticallyExposedPerson> (instance, "variable 'instance' is a PoliticallyExposedPerson");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'StartedDate'
        /// </summary>
        [Test]
        public void StartedDateTest()
        {
            // TODO unit test for the property 'StartedDate'
        }
        /// <summary>
        /// Test the property 'EndedDate'
        /// </summary>
        [Test]
        public void EndedDateTest()
        {
            // TODO unit test for the property 'EndedDate'
        }
        /// <summary>
        /// Test the property 'SenderId'
        /// </summary>
        [Test]
        public void SenderIdTest()
        {
            // TODO unit test for the property 'SenderId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
