/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing Sender
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SenderTests
    {
        // TODO uncomment below to declare an instance variable for Sender
        //private Sender instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Sender
            //instance = new Sender();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Sender
        /// </summary>
        [Test]
        public void SenderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Sender
            //Assert.IsInstanceOfType<Sender> (instance, "variable 'instance' is a Sender");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'PhoneCountry'
        /// </summary>
        [Test]
        public void PhoneCountryTest()
        {
            // TODO unit test for the property 'PhoneCountry'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Test]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'AddressDescription'
        /// </summary>
        [Test]
        public void AddressDescriptionTest()
        {
            // TODO unit test for the property 'AddressDescription'
        }
        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Test]
        public void IdentificationNumberTest()
        {
            // TODO unit test for the property 'IdentificationNumber'
        }
        /// <summary>
        /// Test the property 'IdentificationType'
        /// </summary>
        [Test]
        public void IdentificationTypeTest()
        {
            // TODO unit test for the property 'IdentificationType'
        }
        /// <summary>
        /// Test the property 'Lang'
        /// </summary>
        [Test]
        public void LangTest()
        {
            // TODO unit test for the property 'Lang'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Test]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Test]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'Occupation'
        /// </summary>
        [Test]
        public void OccupationTest()
        {
            // TODO unit test for the property 'Occupation'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Test]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'LegalEntityType'
        /// </summary>
        [Test]
        public void LegalEntityTypeTest()
        {
            // TODO unit test for the property 'LegalEntityType'
        }
        /// <summary>
        /// Test the property 'RegistrationDate'
        /// </summary>
        [Test]
        public void RegistrationDateTest()
        {
            // TODO unit test for the property 'RegistrationDate'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Test]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'NatureOfBusiness'
        /// </summary>
        [Test]
        public void NatureOfBusinessTest()
        {
            // TODO unit test for the property 'NatureOfBusiness'
        }
        /// <summary>
        /// Test the property 'SourceOfFunds'
        /// </summary>
        [Test]
        public void SourceOfFundsTest()
        {
            // TODO unit test for the property 'SourceOfFunds'
        }
        /// <summary>
        /// Test the property 'CustomSourceOfFunds'
        /// </summary>
        [Test]
        public void CustomSourceOfFundsTest()
        {
            // TODO unit test for the property 'CustomSourceOfFunds'
        }
        /// <summary>
        /// Test the property 'CoreBusinessActivity'
        /// </summary>
        [Test]
        public void CoreBusinessActivityTest()
        {
            // TODO unit test for the property 'CoreBusinessActivity'
        }
        /// <summary>
        /// Test the property 'PurposeOfOpeningAccount'
        /// </summary>
        [Test]
        public void PurposeOfOpeningAccountTest()
        {
            // TODO unit test for the property 'PurposeOfOpeningAccount'
        }
        /// <summary>
        /// Test the property 'OfficePhone'
        /// </summary>
        [Test]
        public void OfficePhoneTest()
        {
            // TODO unit test for the property 'OfficePhone'
        }
        /// <summary>
        /// Test the property 'VatRegistrationNumber'
        /// </summary>
        [Test]
        public void VatRegistrationNumberTest()
        {
            // TODO unit test for the property 'VatRegistrationNumber'
        }
        /// <summary>
        /// Test the property 'FinancialRegulator'
        /// </summary>
        [Test]
        public void FinancialRegulatorTest()
        {
            // TODO unit test for the property 'FinancialRegulator'
        }
        /// <summary>
        /// Test the property 'RegulatoryLicenceNumber'
        /// </summary>
        [Test]
        public void RegulatoryLicenceNumberTest()
        {
            // TODO unit test for the property 'RegulatoryLicenceNumber'
        }
        /// <summary>
        /// Test the property 'ContactPersonEmail'
        /// </summary>
        [Test]
        public void ContactPersonEmailTest()
        {
            // TODO unit test for the property 'ContactPersonEmail'
        }
        /// <summary>
        /// Test the property 'TradingCountry'
        /// </summary>
        [Test]
        public void TradingCountryTest()
        {
            // TODO unit test for the property 'TradingCountry'
        }
        /// <summary>
        /// Test the property 'TradingAddress'
        /// </summary>
        [Test]
        public void TradingAddressTest()
        {
            // TODO unit test for the property 'TradingAddress'
        }
        /// <summary>
        /// Test the property 'TradingName'
        /// </summary>
        [Test]
        public void TradingNameTest()
        {
            // TODO unit test for the property 'TradingName'
        }
        /// <summary>
        /// Test the property 'NumberMonthlyTransactions'
        /// </summary>
        [Test]
        public void NumberMonthlyTransactionsTest()
        {
            // TODO unit test for the property 'NumberMonthlyTransactions'
        }
        /// <summary>
        /// Test the property 'AmountMonthlyTransactions'
        /// </summary>
        [Test]
        public void AmountMonthlyTransactionsTest()
        {
            // TODO unit test for the property 'AmountMonthlyTransactions'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'OnboardingStatus'
        /// </summary>
        [Test]
        public void OnboardingStatusTest()
        {
            // TODO unit test for the property 'OnboardingStatus'
        }
        /// <summary>
        /// Test the property 'PoliticallyExposedPeople'
        /// </summary>
        [Test]
        public void PoliticallyExposedPeopleTest()
        {
            // TODO unit test for the property 'PoliticallyExposedPeople'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'CityOfBirth'
        /// </summary>
        [Test]
        public void CityOfBirthTest()
        {
            // TODO unit test for the property 'CityOfBirth'
        }
        /// <summary>
        /// Test the property 'CountryOfBirth'
        /// </summary>
        [Test]
        public void CountryOfBirthTest()
        {
            // TODO unit test for the property 'CountryOfBirth'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'SalesLeadId'
        /// </summary>
        [Test]
        public void SalesLeadIdTest()
        {
            // TODO unit test for the property 'SalesLeadId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
