/* 
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;
using TransferZero.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing TransactionReqLimitsResponseObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionReqLimitsResponseObjectTests
    {
        // TODO uncomment below to declare an instance variable for TransactionReqLimitsResponseObject
        //private TransactionReqLimitsResponseObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionReqLimitsResponseObject
            //instance = new TransactionReqLimitsResponseObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionReqLimitsResponseObject
        /// </summary>
        [Test]
        public void TransactionReqLimitsResponseObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionReqLimitsResponseObject
            //Assert.IsInstanceOfType<TransactionReqLimitsResponseObject> (instance, "variable 'instance' is a TransactionReqLimitsResponseObject");
        }


        /// <summary>
        /// Test the property 'Minimum'
        /// </summary>
        [Test]
        public void MinimumTest()
        {
            // TODO unit test for the property 'Minimum'
        }
        /// <summary>
        /// Test the property 'Maximum'
        /// </summary>
        [Test]
        public void MaximumTest()
        {
            // TODO unit test for the property 'Maximum'
        }

    }

}
