/* 
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TransferZero.Sdk.Client;
using TransferZero.Sdk.Api;
using TransferZero.Sdk.Model;

namespace TransferZero.Sdk.Test
{
    /// <summary>
    ///  Class for testing DlocalBalanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DlocalBalanceApiTests
    {
        private DlocalBalanceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DlocalBalanceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DlocalBalanceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DlocalBalanceApi
            //Assert.IsInstanceOfType(typeof(DlocalBalanceApi), instance, "instance is a DlocalBalanceApi");
        }

        
        /// <summary>
        /// Test GetBalance
        /// </summary>
        [Test]
        public void GetBalanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBalance();
            //Assert.IsInstanceOf<DlocalBalanceResponse> (response, "response is DlocalBalanceResponse");
        }
        
    }

}
